#!/bin/bash

# Variables
PROJECT_ROOT="/home/kevin/stoneboatpottery.ca"
CURRENT_FOLDER="$PROJECT_ROOT/html"
RELEASE_NUMBER=`date +%d%m%y-%H%M%S`
RELEASE_FOLDER="$PROJECT_ROOT/releases/$RELEASE_NUMBER"

# Create folder for current release
echo "** Deploying stoneboatpottery.ca release number $RELEASE_NUMBER"
if [ -e "$RELEASE_FOLDER" ]
then
  echo "** ERROR: Release folder already exists."
  exit 1
fi

mkdir "$RELEASE_FOLDER"

# Checkout project into it
git clone git://github.com/kimos/stoneboat_pottery.git "$RELEASE_FOLDER"

# Copy in config files
if [ -e "$CURRENT_FOLDER/public/images" ]
then
  echo "** Importing config files"
  cp "$CURRENT_FOLDER/config/database.yml" "$RELEASE_FOLDER/config/"
else
  echo "** WARNING: Cannot find config files to import from current version"
fi

# Copy in media files
if [ -e "$CURRENT_FOLDER/public/images" ]
then
  echo "** Importing images"
  cp -r "$CURRENT_FOLDER/public/images/attachment" "$RELEASE_FOLDER/public/images"
else
  echo "** WARNING: Cannot find images to import from current version"
fi

# Run migrations
echo "** Running migrations"
cd "$RELEASE_FOLDER"
rake db:migrate RAILS_ENV=production

# Update symlink
echo "** Creating link to new release"
rm "$CURRENT_FOLDER"
ln -s "$RELEASE_FOLDER" "$CURRENT_FOLDER"

# Get rid of old verions
echo "** WARNING: Old releases are not yet being removed"

# Restart server
# This may not be necessary
echo "** Restarting httpd"
sudo /etc/init.d/httpd graceful

# Done
echo "** Deployed successfully"

